[window]
opacity = 0.8
padding.x = 0
padding.y = 0

[font]
normal.family = "SauceCodePro Nerd Font Mono"
normal.style = "Medium"
size = 15

[keyboard]
# Placeholder example for me to remember
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]
